// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkLE2Mwipj2aPv8BnmSbhnQich8ExOCQU',
    appId: '1:49020959261:web:1d5d22c76b00954be524f4',
    messagingSenderId: '49020959261',
    projectId: 'flutterdemo-fcf30',
    authDomain: 'flutterdemo-fcf30.firebaseapp.com',
    storageBucket: 'flutterdemo-fcf30.firebasestorage.app',
    measurementId: 'G-RFC9LB3EBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzIhmuKWWt07FazzSgzgjoYh_qSUpBmKQ',
    appId: '1:49020959261:android:404f357481c2bc33e524f4',
    messagingSenderId: '49020959261',
    projectId: 'flutterdemo-fcf30',
    storageBucket: 'flutterdemo-fcf30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbj6JUAkdKD8Hh2hzqkBl3HjrIFMEXcpU',
    appId: '1:49020959261:ios:1d7f370a2036c61ee524f4',
    messagingSenderId: '49020959261',
    projectId: 'flutterdemo-fcf30',
    storageBucket: 'flutterdemo-fcf30.firebasestorage.app',
    iosBundleId: 'com.example.demoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbj6JUAkdKD8Hh2hzqkBl3HjrIFMEXcpU',
    appId: '1:49020959261:ios:1d7f370a2036c61ee524f4',
    messagingSenderId: '49020959261',
    projectId: 'flutterdemo-fcf30',
    storageBucket: 'flutterdemo-fcf30.firebasestorage.app',
    iosBundleId: 'com.example.demoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkLE2Mwipj2aPv8BnmSbhnQich8ExOCQU',
    appId: '1:49020959261:web:91b30b75f49c5248e524f4',
    messagingSenderId: '49020959261',
    projectId: 'flutterdemo-fcf30',
    authDomain: 'flutterdemo-fcf30.firebaseapp.com',
    storageBucket: 'flutterdemo-fcf30.firebasestorage.app',
    measurementId: 'G-E3LXGXWETY',
  );
}
